### ISSUE TITLE
"TypeError: Cannot read property 'inherits' of undefined" in version 2.5.0

### ISSUE THREAD

**Issue by x3rAx** [codeshifu/sync-dotenv#28]
**First things first**: Great work, thanks for this tool :smiley:

I encounter the following error when I try to run `sync-dotenv`  in version `2.5.0`:

```
TypeError: Cannot read property 'inherits' of undefined                                                            │
    at Object.<anonymous> (/home/x3ro/.local/opt/n/lib/node_modules/sync-dotenv/dist/index.js:2:16669)             │found 0 vulnerabilities
    at Module._compile (internal/modules/cjs/loader.js:1147:30)                                                    │
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)                                      │x3ro@K1STE:~/Projects/x3ro/hacker-news-bot$ ^C
    at Module.load (internal/modules/cjs/loader.js:996:32)                                                         │x3ro@K1STE:~/Projects/x3ro/hacker-news-bot$ tail -f .env.example 
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)                                               │ # Copy this file to `.env` and change values as needed.
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)                            │
    at internal/main/run_main_module.js:17:47
```

I tried installing it globally, in a project and even in an empty project.

Installing `sync-dotenv@2.4.0` works flawlessly.

**Comment by codeshifu** [comment]
that suck! I'm looking at this now @x3rAx

**Comment by codeshifu** [comment]
@x3rAx  This has been fixed!

There was a problem with the release build of the library using [microbundle][https://www.npmjs.com/package/microbundle). I've resorted to using [parcel](https://parceljs.org/). Thanks for reporting

Please consider migrating to [v2.6+](https://www.npmjs.com/package/sync-dotenv/v/2.6.0)

**Comment by x3rAx** [comment]
Wooow, I totally missed the notification for that one. I can confirm that it works with v2.5.1 and the currently latest version (v2.6.0).

Thanks for the update :slightly_smiling_face:
